name: Node.js CI + Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with: 
          version: 8
      - name: Use Node.js Active LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies (yarn)
        run: pnpm i
      - name: Build assets
        run: pnpm build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
           name: 'github-pages'
           path: dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
