name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        # use tag version as release
        name: Release ${{ github.ref_name }}
        body: 
          ${{ github.event.head_commit.message }}
        artifacts: dist/index.user.js
