name: Release Userscript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:    
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: pages
    steps:  
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            ${{ github.event.head_commit.message }}
          artifacts: "./dist/index.user.js"
